# numpy practise session

In [1]:
#pip install numpy

In [2]:
# import this library in J.notebook
import numpy as np

# Creating an array using numpy

In [5]:
food= np.array(["Pakora", "Samosa","Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [6]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [7]:
type(price)

numpy.ndarray

In [8]:
type(food)

numpy.ndarray

In [10]:
len(food)

3

In [12]:
price[2]

5

In [13]:
price[0:]

array([5, 5, 5])

In [14]:
food[1]

'Samosa'

In [15]:
price.mean()

5.0

In [16]:
# zeros 
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
#empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [21]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [24]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
# table 0f 5
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [27]:
# table of 9
np.arange(0,99,9)

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90])

In [32]:
# line space
np.linspace(1,10,num=6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [35]:
# specify your data type
np.ones(50,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [36]:
np.ones(50,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# array fuctions

In [39]:
a =np.array([10,12,15,2,6,4,100,0,5,10,3])
a

array([ 10,  12,  15,   2,   6,   4, 100,   0,   5,  10,   3])

In [42]:
a.sort()
a

array([  0,   2,   3,   4,   5,   6,  10,  10,  12,  15, 100])

In [45]:
b =np.array([1,12,13,1,5,45,67,78,90,99])
b

array([ 1, 12, 13,  1,  5, 45, 67, 78, 90, 99])

In [49]:
c = np.concatenate((a,b,))
c

array([  0,   2,   3,   4,   5,   6,  10,  10,  12,  15, 100,   1,  12,
        13,   1,   5,  45,  67,  78,  90,  99])

In [50]:
c.sort()
c

array([  0,   1,   1,   2,   3,   4,   5,   5,   6,  10,  10,  12,  12,
        13,  15,  45,  67,  78,  90,  99, 100])

# 2-D arrays

In [59]:
x = np.array([[1,2],[5,4]])
x

array([[1, 2],
       [5, 4]])

In [56]:
y = np.array([[6,7,],[7,8]])
y

array([[6, 7],
       [7, 8]])

In [60]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [5, 4],
       [6, 7],
       [7, 8]])

In [61]:
np.concatenate((x,y), axis=1)

array([[1, 2, 6, 7],
       [5, 4, 7, 8]])

In [63]:
a = np.array([[[0,1,2,3],
              [4,5,6,7]],
              
              [[0,1,2,3],
              [4,5,6,7]],
              
              [[0,1,2,3],
              [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [64]:
# to find the no. of dimensions
a.ndim

3

In [66]:
b =np.array([[5,6,7],
            [8,9,10],
            [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [67]:
b.ndim

2

In [68]:
# size (no. of elements)
a.size

24

In [69]:
# shape
a.shape

(3, 2, 4)

In [75]:
a = np.arange(9) #3*3=9
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
# reshape

b= a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
# reshape
np.reshape(a,newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [78]:
# convert 1D into 2D
a= np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
a.shape

(9,)

In [80]:
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [81]:
b.shape

(1, 9)

In [83]:
# column wise
c = a[np.newaxis, :]
c

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [84]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
# indexing
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [90]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [92]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [95]:
a.sum()

45

In [96]:
a.mean()

5.0